### ISSUE TITLE
Machine Learning

### ISSUE THREAD

**Issue by mayuso** [AbeelLab/macaw2#4]
**I am really sorry for posting this here, I know it does not belong here and I will close this Issue as soon as possible.**

I have bee using JavaML for some months now to learn about machine learning, but found that it hasn´t been updated in more than 2 years.

Is JavaMLm 0.1.8 (or 0.2.0) planned to be released some time or is JavaML an old project already abandoned?

Anyway, I hope you read and asnwer this, thank you for creating JavaML and all the other awesome projects. Sorry again for creating this Issue.

**Comment by thomasabeel** [comment]
Contact me by e-mail with Java-ML related inquiries. I'd like to keep Java-ML going, but updates have indeed been very slow.

**Comment by mayuso** [comment]
Yes, that was the plan, but could not find your e-mail. Sorry.

Edit: Found it :)
